from pydantic import BaseModel
from typing import Optional, List, Union
from datetime import date
from enum import Enum
from uuid import UUID


class Status(str, Enum):
    PENDING = "Pending"
    IN_PROGRESS = "In Progress"
    DONE = "Done"

class BaseTask(BaseModel):
    description: Optional[str] = None
    status: Optional[str] = None
    priority: Optional[str] = None
    category: Optional[str] = None
    due_date: Optional[date] = None
    partner_id: Optional[Union[int, List[int]]] = None

class TaskCreate(BaseTask):
    title: str  # Required only on create

class TaskUpdate(BaseTask):
    title: Optional[str] = None  # Optional on update
    
class Task(BaseTask):
    task_id: int  # Task ID, required for existing tasks
    created_at: date # creation date, auto-generated by the server 
    completed_at: Optional[date] = None # auto-generated by the server when the task's status = 'completed'
