from pydantic import BaseModel
from typing import Optional, List, Union
from datetime import date
from enum import Enum


class Status(str, Enum):
    PENDING = "Pending"
    IN_PROGRESS = "In Progress"
    DONE = "Done"

class BaseTask(BaseModel):
    title: Optional[str] = None
    description: Optional[str] = None
    status: Optional[Status] = None  # e.g., 'pending', 'in_progress', 'completed'
    priority: Optional[str] = None # e.g., 1 for high, 2 for medium, 3 for low
    category: Optional[str] = None # e.g 'routine maintenance', 'long-term improvements', 'urgent maintenance' etc
    due_date: Optional[date] = None # ISO format date string, e.g., '2023-10-01'
    partner_id: Optional[Union[int, List[int]]] = None  # partner_id\s assigned with the task

class Task(BaseTask):
    id: int  # Task ID, required for existing tasks
    created_at: date # creation date, auto-generated by the server 
    completed_at: Optional[date] = None # auto-generated by the server when the task's status = 'completed'
